name: sajilo_restro_sewa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: ^3.6.0 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  flutter_secure_storage: ^10.3.1
  socket_io_client: ^3.0.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  intl: ^0.20.2
  dio: ^5.9.2
  shimmer: ^3.0.0
  fl_chart: ^1.2.0
  image_picker: ^1.2.2
  permission_handler: ^12.0.3
  flutter_local_notifications: ^22.0.0
  vibration: ^3.2.0
  flutter_ringtone_player: ^4.0.0+4
  app_links: ^7.1.2
  device_info_plus: ^13.1.0
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  msix: ^3.18.0

dependency_overrides:
  permission_handler_windows: ^0.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
  linux:
    generate: true
    image_path: "assets/icons/icon.png"
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash_icon.png"
  android: true
  ios: true
  web: false
  android_12:
    image: "assets/icons/splash_icon.png"
    icon_background_color: "#ffffff"